# 游戏玩家付费金额预测大赛 - 数据探索

In [8]:
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [9]:
path_raw = '../data/raw/'
path_new = '../data/new/'

In [10]:
raw_train = pd.read_csv(path_raw + 'tap_fun_train.csv')
raw_train.head()

,user_id,register_time,wood_add_value,wood_reduce_value,stone_add_value,stone_reduce_value,ivory_add_value,ivory_reduce_value,meat_add_value,meat_reduce_value,...,pvp_battle_count,pvp_lanch_count,pvp_win_count,pve_battle_count,pve_lanch_count,pve_win_count,avg_online_minutes,pay_price,pay_count,prediction_pay_price
0,1,2018-02-02 19:47:15,20125.0,3700.0,0.0,0.0,0.0,0.0,16375.0,2000.0,...,0,0,0,0,0,0,0.333333,0.0,0,0.0
1,1593,2018-01-26 00:01:05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0.333333,0.0,0,0.0
2,1594,2018-01-26 00:01:58,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,1.166667,0.0,0,0.0
3,1595,2018-01-26 00:02:13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,3.166667,0.0,0,0.0
4,1596,2018-01-26 00:02:46,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,2.333333,0.0,0,0.0

In [11]:
col = 'sr_rss_help_bonus_level'
print('\n%s 属性的不同取值和出现的次数' % col)
print(raw_train[col].value_counts())

sr_rss_help_bonus_level 属性的不同取值和出现的次数
0    2288004
8          1
5          1
1          1
Name: sr_rss_help_bonus_level, dtype: int64

In [13]:
# sr_rss_help_bonus_level > 0 的是否付费？
tmp_df = raw_train.loc[raw_train['sr_rss_help_bonus_level'] > 0, ['sr_rss_help_bonus_level','pay_price','pay_count','prediction_pay_price']]
tmp_df.head()

         sr_rss_help_bonus_level  pay_price  pay_count  prediction_pay_price
1423324                        5    6253.98        102              20261.46
1520367                        8     505.90         10                610.88
1831948                        1    3733.29         71               6343.01

In [5]:
raw_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2288007 entries, 0 to 2288006
Columns: 109 entries, user_id to prediction_pay_price
dtypes: float64(13), int64(95), object(1)
memory usage: 1.9+ GB

In [6]:
train_part, test_part = train_test_split(raw_train, random_state=33, test_size=0.9)
train_part.head()

,user_id,register_time,wood_add_value,wood_reduce_value,stone_add_value,stone_reduce_value,ivory_add_value,ivory_reduce_value,meat_add_value,meat_reduce_value,...,pvp_battle_count,pvp_lanch_count,pvp_win_count,pve_battle_count,pve_lanch_count,pve_win_count,avg_online_minutes,pay_price,pay_count,prediction_pay_price
1736612,2320186,2018-02-07 06:51:15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,3.833333,0.0,0,0.0
2095056,2959017,2018-02-10 16:18:10,129429.0,78242.0,0.0,0.0,6000.0,0.0,152480.0,48626.0,...,0,0,0,2,2,2,3.166667,0.0,0,0.0
207402,242613,2018-02-09 02:40:08,84839.0,52467.0,0.0,0.0,0.0,0.0,22144.0,29600.0,...,0,0,0,0,0,0,2.666667,0.0,0,0.0
1141005,1416097,2018-01-26 09:30:30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0.333333,0.0,0,0.0
521821,680469,2018-02-27 10:04:04,28625.0,7200.0,0.0,0.0,0.0,0.0,33625.0,3930.0,...,0,0,0,0,0,0,1.000000,0.0,0,0.0

In [7]:
train_part.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 228800 entries, 1736612 to 1989652
Columns: 109 entries, user_id to prediction_pay_price
dtypes: float64(13), int64(95), object(1)
memory usage: 192.0+ MB

In [8]:
# 训练集的1/10，样本数= 228800
train_part.to_csv(path_new + 'train=0.1.csv', index=False)

In [3]:
train_part1 = pd.read_csv(path_new + 'train=0.1.csv')
train_part1.head()

,user_id,register_time,wood_add_value,wood_reduce_value,stone_add_value,stone_reduce_value,ivory_add_value,ivory_reduce_value,meat_add_value,meat_reduce_value,...,pvp_battle_count,pvp_lanch_count,pvp_win_count,pve_battle_count,pve_lanch_count,pve_win_count,avg_online_minutes,pay_price,pay_count,prediction_pay_price
0,2320186,2018-02-07 06:51:15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,3.833333,0.0,0,0.0
1,2959017,2018-02-10 16:18:10,129429.0,78242.0,0.0,0.0,6000.0,0.0,152480.0,48626.0,...,0,0,0,2,2,2,3.166667,0.0,0,0.0
2,242613,2018-02-09 02:40:08,84839.0,52467.0,0.0,0.0,0.0,0.0,22144.0,29600.0,...,0,0,0,0,0,0,2.666667,0.0,0,0.0
3,1416097,2018-01-26 09:30:30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0.333333,0.0,0,0.0
4,680469,2018-02-27 10:04:04,28625.0,7200.0,0.0,0.0,0.0,0.0,33625.0,3930.0,...,0,0,0,0,0,0,1.000000,0.0,0,0.0

In [4]:
train_part1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 228800 entries, 0 to 228799
Columns: 109 entries, user_id to prediction_pay_price
dtypes: float64(13), int64(95), object(1)
memory usage: 190.3+ MB

In [5]:
#对数值型特征，观察其取值范围及直方图
cat_features = train_part1.select_dtypes(include = ["int64"]).columns
for col in cat_features:
    print('\n%s 属性的不同取值和出现的次数' % col)
    print(train_part1[col].value_counts())

user_id 属性的不同取值和出现的次数
1052670    1
2814728    1
2253594    1
162585     1
1182487    1
2753302    1
2233108    1
1005165    1
1194769    1
1717008    1
784238     1
2810634    1
2816777    1
695045     1
2245406    1
178945     1
2798336    1
2968319    1
875261     1
1515186    1
2978552    1
1377014    1
862963     1
336626     1
383725     1
905964     1
678685     1
768801     1
391913     1
2751669    1
          ..
2735516    1
624027     1
212428     1
1779151    1
1826256    1
2872785    1
2981380    1
876032     1
1746431    1
701949     1
165371     1
194037     1
2809328    1
2762223    1
144877     1
1183210    1
681447     1
2256358    1
3148227    1
1725921    1
1727968    1
241118     1
2799179    1
2330074    1
1912135    1
2352599    1
2878934    1
670056     1
2556995    1
1058821    1
Name: user_id, Length: 228800, dtype: int64

infantry_add_value 属性的不同取值和出现的次数
0        201745
10         1110
65          894
20          781
110         779
70          703
40          619
50          550
75          393
35          385
60          382
85          380
135         352
25          335
80          321
30          258
120         245
90          242
130         231
95          223
150         218
100         208
55          207
140         193
145         181
45          173
210         169
180         163
220         144
105         142
          ...
14251         1
1837          1
3631          1
1709          1
3756          1
1504          1
1581          1
3628          1
3500          1
4556          1
5999          1
2479          1
6701          1
3948          1
1582          1
1454          1
7597          1
9642          1
1133          1
5292          1
3119          1
3809          1
5164          1
3916          1
13803         1
5036          1
13096         1
1773          1
8142          1
3629          1
Name: infantry_add_value, Length: 4663, dtype: int64

infantry_reduce_value 属性的不同取值和出现的次数
0        172346
200       12186
210        2358
18         1309
19          580
17          422
2           403
275         393
20          354
250         315
10          276
320         253
1           250
220         245
280         240
16          237
260         230
230         212
21          205
37          199
35          184
15          180
36          177
25          174
14          168
27          167
22          166
32          163
34          161
23          160
          ...
28368         1
11048         1
4783          1
6830          1
3804          1
13995         1
1709          1
19111         1
4703          1
2607          1
6701          1
8746          1
4447          1
10840         1
2652          1
4396          1
8490          1
6750          1
14505         1
7854          1
22693         1
31442         1
8234          1
9177          1
14251         1
5935          1
13275         1
10025         1
22311         1
8772          1
Name: infantry_reduce_value, Length: 5878, dtype: int64

cavalry_add_value 属性的不同取值和出现的次数
0        201970
20         2154
25          707
70          643
110         618
65          563
50          544
60          509
40          466
85          426
35          354
30          341
10          335
135         313
75          290
90          272
80          267
55          260
120         249
130         248
100         241
150         214
95          198
140         197
145         161
180         159
220         157
160         153
105         153
170         144
          ...
7621          1
1222          1
2887          1
6981          1
5317          1
1351          1
4171          1
15808         1
1992          1
10060         1
1864          1
9932          1
9804          1
5578          1
60757         1
1224          1
13390         1
5194          1
2889          1
6859          1
2761          1
4682          1
4170          1
1991          1
8132          1
1863          1
1735          1
5701          1
3526          1
4541          1
Name: cavalry_add_value, Length: 4523, dtype: int64

cavalry_reduce_value 属性的不同取值和出现的次数
0        192886
20         1828
1           829
2           683
3           537
4           516
5           443
6           422
25          373
7           357
8           336
10          317
9           286
70          269
60          258
85          251
12          249
90          243
13          237
11          234
30          227
15          217
16          203
14          201
40          193
18          182
17          166
19          165
130         159
55          147
          ...
6963          1
4914          1
2655          1
33568         1
4786          1
3761          1
16055         1
4659          1
4060          1
2608          1
12727         1
10676         1
5599          1
4403          1
7774          1
1757          1
12471         1
3932          1
2224          1
2271          1
4147          1
6194          1
2013          1
2096          1
8115          1
14134         1
10036         1
10459         1
4316          1
10693         1
Name: cavalry_reduce_value, Length: 5578, dtype: int64

shaman_add_value 属性的不同取值和出现的次数
0        214154
65          513
110         328
135         263
75          255
50          188
145         172
85          157
70          131
80          124
95          123
130         121
150         119
120         110
185         107
105          88
140          80
90           76
1            71
100          71
165          70
155          65
125          61
2            58
3            55
115          51
170          50
160          50
290          47
220          46
          ...
8513          1
16589         1
2116          1
8135          1
3653          1
11713         1
4222          1
2119          1
10435         1
2503          1
12865         1
4421          1
14656         1
2246          1
12353         1
8005          1
3783          1
7877          1
24141         1
3655          1
11843         1
9538          1
3143          1
3015          1
5060          1
6853          1
10947         1
6725          1
4676          1
2047          1
Name: shaman_add_value, Length: 4282, dtype: int64

shaman_reduce_value 属性的不同取值和出现的次数
0        208009
65          325
50          230
110         222
135         194
75          174
3           137
2           136
1           133
130         116
145         111
4           105
70          101
85           98
6            94
140          94
120          91
5            89
150          87
95           84
290          80
80           76
12           76
280          75
7            72
240          72
9            71
10           70
220          69
100          68
          ...
5572          1
19406         1
7236          1
6987          1
16320         1
4810          1
2761          1
4682          1
2377          1
10445         1
8396          1
6219          1
24524         1
6085          1
10179         1
14273         1
1863          1
17487         1
10051         1
14145         1
16192         1
1735          1
11970         1
11842         1
1479          1
3526          1
1351          1
1223          1
7364          1
3006          1
Name: shaman_reduce_value, Length: 5150, dtype: int64

wound_infantry_add_value 属性的不同取值和出现的次数
0        196247
210         926
18          360
275         292
130         285
19          225
250         221
17          198
1           196
2           184
20          181
16          168
320         163
280         157
260         149
10          138
25          130
22          129
15          128
21          126
30          122
29          120
270         118
35          112
200         112
285         110
32          109
3           108
23          108
40          107
          ...
1768          1
8494          1
10543         1
4520          1
30438         1
5738          1
10671         1
6697          1
8771          1
13806         1
6825          1
1512          1
1384          1
5032          1
5800          1
7081          1
2502          1
2987          1
5160          1
4549          1
3115          1
5288          1
10690         1
3243          1
9390          1
5226          1
7147          1
3499          1
3416          1
1491          1
Name: wound_infantry_add_value, Length: 4582, dtype: int64

wound_infantry_reduce_value 属性的不同取值和出现的次数
0        215685
1           117
18          114
210          94
2            85
19           81
16           76
17           76
10           68
3            66
4            61
7            60
14           59
20           57
22           55
5            55
21           49
9            48
15           47
6            46
8            43
23           43
12           43
40           41
25           41
13           41
27           40
35           39
11           37
30           37
          ...
6331          1
17121         1
2105          1
4843          1
4022          1
3894          1
1719          1
4971          1
3638          1
5557          1
5429          1
8636          1
696           1
14702         1
1848          1
6202          1
4073          1
2104          1
4025          1
20401         1
5946          1
3641          1
2408          1
1592          1
10220         1
1208          1
13374         1
3129          1
4331          1
1855          1
Name: wound_infantry_reduce_value, Length: 3934, dtype: int64

wound_cavalry_add_value 属性的不同取值和出现的次数
0        198775
20         1246
1           510
2           493
4           407
3           393
5           374
6           336
7           294
8           290
10          277
25          257
9           247
12          213
70          201
15          201
19          201
85          197
11          196
16          190
90          190
18          186
13          183
14          179
60          176
17          174
30          147
40          142
130         125
22          122
          ...
3908          1
7878          1
1733          1
5703          1
7750          1
3396          1
11200         1
3271          1
5572          1
1863          1
967           1
3910          1
8004          1
10051         1
3782          1
7876          1
11970         1
7748          1
1095          1
3014          1
1606          1
5061          1
9155          1
4805          1
6852          1
2502          1
1862          1
8005          1
3655          1
2494          1
Name: wound_cavalry_add_value, Length: 4393, dtype: int64

wound_cavalry_reduce_value 属性的不同取值和出现的次数
0        216096
1           189
2           164
20          161
3           139
4           130
5           128
6           100
9            93
8            91
10           86
7            83
14           82
11           74
15           68
12           64
19           55
18           51
17           51
16           51
23           49
13           47
24           43
22           40
21           40
70           40
25           39
85           38
30           37
90           37
          ...
2761          1
4554          1
4170          1
2121          1
8004          1
10051         1
3782          1
7876          1
1608          1
4171          1
38616         1
2632          1
1610          1
13516         1
1226          1
5192          1
19139         1
12876         1
2507          1
2251          1
4296          1
24258         1
9677          1
3400          1
5323          1
1225          1
3272          1
3016          1
6730          1
1086          1
Name: wound_cavalry_reduce_value, Length: 3842, dtype: int64

wound_shaman_add_value 属性的不同取值和出现的次数
0        210365
65          275
50          191
110         186
135         160
75          154
1           140
2           124
3           123
4            97
145          95
130          90
6            87
5            86
85           85
7            84
70           80
12           78
95           77
120          77
9            72
11           72
140          71
150          70
10           67
290          67
8            67
80           66
100          64
185          56
          ...
4291          1
4986          1
2240          1
8261          1
4163          1
1016          1
4033          1
1985          1
2809          1
7745          1
4800          1
1474          1
7617          1
1346          1
19659         1
5184          1
13252         1
3011          1
6849          1
12868         1
2115          1
2627          1
4672          1
14789         1
2499          1
4416          1
2243          1
8262          1
14405         1
2047          1
Name: wound_shaman_add_value, Length: 4307, dtype: int64

wound_shaman_reduce_value 属性的不同取值和出现的次数
0        218764
1           117
2            94
3            87
4            78
5            54
12           54
7            52
11           52
6            50
9            47
10           41
65           41
8            39
17           37
16           36
50           36
110          34
14           31
130          29
13           29
31           26
21           26
85           25
22           25
135          24
105          24
150          22
18           22
15           22
          ...
841           1
4683          1
2632          1
4555          1
2504          1
329           1
2376          1
8397          1
3656          1
1609          1
3912          1
1865          1
2891          1
4936          1
2763          1
714           1
2635          1
10703         1
8654          1
2507          1
2379          1
8398          1
12492         1
2251          1
6345          1
10319         1
8270          1
4168          1
1993          1
831           1
Name: wound_shaman_reduce_value, Length: 3742, dtype: int64

general_acceleration_add_value 属性的不同取值和出现的次数
0         139356
3          15151
60          8712
50          8484
110         2814
6           2704
660         2146
53          1898
240         1868
63          1493
15           882
180          833
120          755
9            596
320          594
18           593
66           376
113          366
80           361
56           354
140          337
230          311
170          291
20           263
663          249
21           237
75           219
30           216
260          204
720          188
           ...
3394           1
5318           1
3525           1
114814         1
54239          1
6213           1
4164           1
6087           1
8006           1
3908           1
5831           1
20044          1
3396           1
3268           1
40022          1
5191           1
21455          1
7623           1
13251          1
9025           1
2756           1
4551           1
4423           1
4167           1
1988           1
1860           1
5830           1
3781           1
3653           1
3262           1
Name: general_acceleration_add_value, Length: 5787, dtype: int64

general_acceleration_reduce_value 属性的不同取值和出现的次数
0        172498
1          7193
3          5789
60         2571
2          2307
6          1373
50          771
61          768
15          726
63          512
53          451
49          388
62          360
9           331
5           325
18          316
120         295
30          286
109         274
110         246
75          235
10          207
4           202
20          199
86          196
66          192
12          181
56          174
180         168
26          166
          ...
10843         1
2527          1
4773          1
6621          1
8995          1
2854          1
12760         1
2982          1
6493          1
5157          1
17207         1
5957          1
3366          1
3494          1
6443          1
7716          1
3622          1
2622          1
3750          1
14273         1
5855          1
9945          1
18133         1
7774          1
2494          1
3548          1
5471          1
57524         1
3420          1
3650          1
Name: general_acceleration_reduce_value, Length: 4745, dtype: int64

building_acceleration_add_value 属性的不同取值和出现的次数
0        117442
1         20830
202       12234
352        9916
351        7569
207        5638
307        5165
337        3131
237        2179
100        1849
312        1718
322        1532
212        1380
342        1322
317        1130
217        1092
5          1085
357        1017
222         906
105         860
327         819
347         705
412         631
362         589
201         563
110         551
10          543
242         535
367         530
332         504
          ...
4150          1
52            1
1971          1
12086         1
3762          1
5430          1
1587          1
1459          1
3378          1
9318          1
5297          1
7344          1
4278          1
2915          1
4406          1
31035         1
6583          1
8752          1
6521          1
6711          1
4320          1
4790          1
11185         1
10213         1
4064          1
9392          1
16230         1
5302          1
5987          1
8188          1
Name: building_acceleration_add_value, Length: 3864, dtype: int64

building_acceleration_reduce_value 属性的不同取值和出现的次数
0        153794
45         4875
337        4209
46         3015
307        2824
1          2413
322        1991
207        1432
82         1245
60         1158
312        1090
292        1080
15         1007
352         990
22          969
317         885
277         840
30          825
237         803
327         698
202         688
342         615
7           584
31          582
357         532
280         521
75          501
5           500
285         490
67          464
          ...
4281          1
22704         1
6253          1
2106          1
12223         1
41256         1
4027          1
3771          1
1722          1
3643          1
1594          1
5688          1
6456          1
4409          1
2362          1
1901          1
3948          1
7790          1
4921          1
1645          1
15164         1
955           1
1467          1
1595          1
1723          1
3692          1
2109          1
4158          1
4286          1
2047          1
Name: building_acceleration_reduce_value, Length: 3530, dtype: int64

reaserch_acceleration_add_value 属性的不同取值和出现的次数
0        115046
50        36797
35        14270
55        11358
5          9321
60         3187
85         2398
10         1914
30         1773
65         1258
90         1109
20         1076
40         1003
15          927
25          721
95          682
45          637
100         610
75          600
80          564
70          473
115         450
140         432
105         419
110         404
120         358
160         333
130         333
145         305
125         294
          ...
3678          1
4144          1
7139          1
13030         1
2785          1
2227          1
8374          1
608           1
4578          1
2483          1
6499          1
10935         1
2015          1
12122         1
7217          1
6448          1
7772          1
3123          1
7345          1
3550          1
3379          1
3507          1
3635          1
3763          1
20411         1
3422          1
4273          1
11610         1
18618         1
4669          1
Name: reaserch_acceleration_add_value, Length: 3576, dtype: int64

reaserch_acceleration_reduce_value 属性的不同取值和出现的次数
0        203454
2          3359
55         2422
5           984
1           898
60          652
30          416
85          382
10          372
35          337
15          296
90          242
65          237
59          226
50          216
45          198
58          197
20          192
40          183
70          169
57          155
61          136
100         131
32          128
43          120
95          115
75          114
19          109
52          108
120         106
          ...
11980         1
10189         1
4296          1
6345          1
2251          1
39129         1
6473          1
2507          1
2635          1
2763          1
10959         1
3019          1
1098          1
1226          1
3274          1
3275          1
3403          1

Name: bd_training_hut_level, dtype: int64

bd_healing_lodge_level 属性的不同取值和出现的次数
0     138472
1      43125
2      12718
3       9007
5       7753
4       7359
6       4979
7       2769
8       1737
9        676
10       132
11        46
12         8
13         7
15         6
14         4
16         1
19         1
Name: bd_healing_lodge_level, dtype: int64

bd_stronghold_level 属性的不同取值和出现的次数
0     93986
1     30696
2     28149
4     17657
5     16023
3     15777
6      9273
7      6868
8      5151
9      3173
10     1320
11      377
12      170
13       84
14       42
15       26
16       10
17        5
18        5
20        4
19        2
21        1
23        1
Name: bd_stronghold_level, dtype: int64

bd_outpost_portal_level 属性的不同取值和出现的次数
0     114546
2      23760
1      22696
4      20034
3      16045
5      11513
7       6746
6       6488
8       3953
9       1765
10       751
11       252
12       116
13        61
14        38
15        13
16         9
18         5
17         3
19         3
21         1
20         1
23         1
Name: bd_outpost_portal_level, dtype: int64

bd_barrack_level 属性的不同取值和出现的次数
0     114193
1      59177
2      16841
4       8595
3       8507
5       6698
6       4500
7       4405
8       3674
9       1535
10       405
11       133
12        72
13        32
14        18
15         6
16         5
17         2
19         2
Name: bd_barrack_level, dtype: int64

bd_healing_spring_level 属性的不同取值和出现的次数
0     161074
1      23231
2      12595
3       8363
4       6122
5       4887
7       4339
6       3992
8       2944
9        937
10       182
11        56
12        28
13        24
14        15
15         8
16         2
18         1
Name: bd_healing_spring_level, dtype: int64

bd_dolmen_level 属性的不同取值和出现的次数
0     160422
1      28840
2       8799
6       5928
5       5044
7       4982
4       4879
3       4640
8       2876
9       1449
10       529
11       217
12        95
13        42
14        26
15        16
16         6
19         5
17         3
18         1
20         1
Name: bd_dolmen_level, dtype: int64

bd_guest_cavern_level 属性的不同取值和出现的次数
0     207284
1       4387
7       2779
8       2695
2       2536
6       2069
3       1905
5       1780
4       1481
9       1374
10       434
11        63
17         3
18         2
13         2
14         2
19         2
12         1
16         1
Name: bd_guest_cavern_level, dtype: int64

bd_warehouse_level 属性的不同取值和出现的次数
0     158938
1      30762
2       8747
3       6525
7       5550
4       4985
5       4352
6       3969
8       3643
9       1022
10       226
11        43
12        23
13         4
14         3
15         3
18         2
16         1
17         1
21         1
Name: bd_warehouse_level, dtype: int64

bd_watchtower_level 属性的不同取值和出现的次数
0     166610
2      16632
1      12361
3      11102
4       5997
5       4333
6       3876
7       3577
8       2958
9        979
10       173
11       114
12        63
13        16
15         4
14         2
21         2
19         1
Name: bd_watchtower_level, dtype: int64

bd_magic_coin_tree_level 属性的不同取值和出现的次数
0     147370
1      30515
2      11750
3       8365
4       7082
5       6585
6       5855
7       5537
8       4063
9       1470
10       163
11        22
12        11
16         4
15         3
14         2
17         2
13         1
Name: bd_magic_coin_tree_level, dtype: int64

bd_hall_of_war_level 属性的不同取值和出现的次数
0     212802
1      11222
2       3127
3       1063
4        384
5        120
6         47
7         23
8          6
9          3
10         2
14         1
Name: bd_hall_of_war_level, dtype: int64

bd_market_level 属性的不同取值和出现的次数
0     176800
1      15544
2       8276
4       7045
3       6584
5       4016
7       3491
8       2813
6       2798
9        957
10       336
11       129
12         8
13         2
14         1
Name: bd_market_level, dtype: int64

bd_hero_gacha_level 属性的不同取值和出现的次数
0     216011
2       2852
1       2309
3       2079
4       1559
5       1268
6       1096
7        906
8        551
9        129
10        30
11         6
12         2
14         1
13         1
Name: bd_hero_gacha_level, dtype: int64

bd_hero_strengthen_level 属性的不同取值和出现的次数
0     216285
2       3130
1       2697
3       2007
4       1438
5       1071
6        898
7        729
8        409
9        112
10        18
11         5
12         1
Name: bd_hero_strengthen_level, dtype: int64

bd_hero_pve_level 属性的不同取值和出现的次数
0     214286
2       2290
1       2023
7       1752
3       1610
6       1575
5       1456
4       1438
8       1313
9        706
10       249
11        77
12        12
13         5
14         5
17         1
15         1
20         1
Name: bd_hero_pve_level, dtype: int64

sr_scout_level 属性的不同取值和出现的次数
0    177944
1     33608
2     12694
3      2229
4      1567
5       651
6       101
7         6
Name: sr_scout_level, dtype: int64

sr_training_speed_level 属性的不同取值和出现的次数
0     201205
1      12320
4       3988
2       3922
5       3715
3       2823
6        735
7         75
9          8
8          7
10         2
Name: sr_training_speed_level, dtype: int64

sr_infantry_tier_2_level 属性的不同取值和出现的次数
0    223379
1      5421
Name: sr_infantry_tier_2_level, dtype: int64

sr_cavalry_tier_2_level 属性的不同取值和出现的次数
0    223555
1      5245
Name: sr_cavalry_tier_2_level, dtype: int64

sr_shaman_tier_2_level 属性的不同取值和出现的次数
0    224316
1      4484
Name: sr_shaman_tier_2_level, dtype: int64

sr_infantry_atk_level 属性的不同取值和出现的次数
0    225746
1      1729
2       738
3       298
4       154
5        57
6        38
7        24
8        14
9         2
Name: sr_infantry_atk_level, dtype: int64

sr_cavalry_atk_level 属性的不同取值和出现的次数
0     225912
1       1625
2        688
3        316
4        123
5         64
7         31
6         26
8         14
10         1
Name: sr_cavalry_atk_level, dtype: int64

sr_shaman_atk_level 属性的不同取值和出现的次数
0     226462
1       1321
2        553
3        241
4        110
5         50
6         29
7         20
8         13
10         1
Name: sr_shaman_atk_level, dtype: int64

sr_infantry_tier_3_level 属性的不同取值和出现的次数
0    228750
1        50
Name: sr_infantry_tier_3_level, dtype: int64

sr_cavalry_tier_3_level 属性的不同取值和出现的次数
0    228751
1        49
Name: sr_cavalry_tier_3_level, dtype: int64

sr_shaman_tier_3_level 属性的不同取值和出现的次数
0    228753
1        47
Name: sr_shaman_tier_3_level, dtype: int64

sr_troop_defense_level 属性的不同取值和出现的次数
0     228766
1         15
3          4
9          3
4          3
11         2
10         2
5          2
7          1
6          1
2          1
Name: sr_troop_defense_level, dtype: int64

sr_infantry_def_level 属性的不同取值和出现的次数
0     228772
1         16
10         4
3          2
9          1
7          1
6          1
5          1
4          1
2          1
Name: sr_infantry_def_level, dtype: int64

sr_cavalry_def_level 属性的不同取值和出现的次数
0     228776
1         16
11         2
3          2
2          2
10         1
7          1
Name: sr_cavalry_def_level, dtype: int64

sr_shaman_def_level 属性的不同取值和出现的次数
0     228776
1         15
10         3
9          2
3          2
7          1
5          1
Name: sr_shaman_def_level, dtype: int64

sr_infantry_hp_level 属性的不同取值和出现的次数
0     228773
8          5
6          4
5          4
10         3
1          3
11         2
4          2
3          2
2          2
Name: sr_infantry_hp_level, dtype: int64

sr_cavalry_hp_level 属性的不同取值和出现的次数
0     228781
1          4
6          3
4          3
2          3
11         2
10         1
8          1
7          1
3          1
Name: sr_cavalry_hp_level, dtype: int64

sr_shaman_hp_level 属性的不同取值和出现的次数
0     228780
1          6
2          4
8          2
7          2
11         1
10         1
9          1
6          1
5          1
4          1
Name: sr_shaman_hp_level, dtype: int64

sr_infantry_tier_4_level 属性的不同取值和出现的次数
0    228794
1         6
Name: sr_infantry_tier_4_level, dtype: int64

sr_cavalry_tier_4_level 属性的不同取值和出现的次数
0    228796
1         4
Name: sr_cavalry_tier_4_level, dtype: int64

sr_shaman_tier_4_level 属性的不同取值和出现的次数
0    228797
1         3
Name: sr_shaman_tier_4_level, dtype: int64

sr_troop_attack_level 属性的不同取值和出现的次数
0     228797
10         1
3          1
1          1
Name: sr_troop_attack_level, dtype: int64

sr_construction_speed_level 属性的不同取值和出现的次数
0    214147
1      9251
2      1864
3      1193
4      1053
5       812
6       314
7       143
8        22
9         1
Name: sr_construction_speed_level, dtype: int64

sr_hide_storage_level 属性的不同取值和出现的次数
0    223438
1      3779
2       952
3       391
4       142
5        54
6        28
7        13
8         3
Name: sr_hide_storage_level, dtype: int64

sr_troop_consumption_level 属性的不同取值和出现的次数
0    224033
1      3294
2       817
3       361
4       174
5        62
6        30
7        23
8         6
Name: sr_troop_consumption_level, dtype: int64

sr_rss_a_prod_levell 属性的不同取值和出现的次数
0    224385
1      2223
2      1317
3       448
4       216
5       139
6        52
7        19
8         1
Name: sr_rss_a_prod_levell, dtype: int64

sr_rss_b_prod_level 属性的不同取值和出现的次数
0    228457
1       173
2        97
3        55
4        14
6         2
5         2
Name: sr_rss_b_prod_level, dtype: int64

sr_rss_c_prod_level 属性的不同取值和出现的次数
0    228706
1        71
2        14
3         7
4         2
Name: sr_rss_c_prod_level, dtype: int64

sr_rss_d_prod_level 属性的不同取值和出现的次数
0    222497
1      4579
2       882
3       377
4       244
5       145
6        57
7        16
8         3
Name: sr_rss_d_prod_level, dtype: int64

sr_rss_a_gather_level 属性的不同取值和出现的次数
0    225864
1      1899
2       562
3       239
4       114
5        67
6        42
7        13
Name: sr_rss_a_gather_level, dtype: int64

sr_rss_b_gather_level 属性的不同取值和出现的次数

0    228549
1       161
2        53
3        22
4        11
6         3
5         1
Name: sr_rss_b_gather_level, dtype: int64

sr_rss_c_gather_level 属性的不同取值和出现的次数
0    228734
1        50
2        12
3         3
4         1
Name: sr_rss_c_gather_level, dtype: int64

sr_rss_d_gather_level 属性的不同取值和出现的次数
0    226080
1      1885
2       503
3       196
4        84
5        29
6        17
7         5
8         1
Name: sr_rss_d_gather_level, dtype: int64

sr_troop_load_level 属性的不同取值和出现的次数
0    226035
1      1064
2       637
3       472
4       294
5       199
6        80
7        19
Name: sr_troop_load_level, dtype: int64

sr_rss_e_gather_level 属性的不同取值和出现的次数
0    228505
1       199
2        64
3        22
4         6
5         2
9         1
6         1
Name: sr_rss_e_gather_level, dtype: int64

sr_rss_e_prod_level 属性的不同取值和出现的次数
0    227897
1       420
2       238
3       171
4        54
5        13
6         5
8         1
7         1
Name: sr_rss_e_prod_level, dtype: int64

sr_outpost_durability_level 属性的不同取值和出现的次数
0    212685
1     11167
2      2399
3      1390
4       803
5       303
6        50
7         3
Name: sr_outpost_durability_level, dtype: int64

sr_outpost_tier_2_level 属性的不同取值和出现的次数
0    218716
1     10084
Name: sr_outpost_tier_2_level, dtype: int64

sr_healing_space_level 属性的不同取值和出现的次数
0     224506
1       2777
2        842
3        573
4         79
5         18
6          3
11         1
8          1
Name: sr_healing_space_level, dtype: int64

sr_gathering_hunter_buff_level 属性的不同取值和出现的次数
0    223583
1      3379
2      1134
3       626
4        64
5        12
7         1
6         1
Name: sr_gathering_hunter_buff_level, dtype: int64

sr_healing_speed_level 属性的不同取值和出现的次数
0    225327
1      2284
2       732
3       418
4        32
5         6
6         1
Name: sr_healing_speed_level, dtype: int64

sr_outpost_tier_3_level 属性的不同取值和出现的次数
0    228586
1       214
Name: sr_outpost_tier_3_level, dtype: int64

sr_alliance_march_speed_level 属性的不同取值和出现的次数
0    228753
1        25
3         9
2         9
4         2
7         1
5         1
Name: sr_alliance_march_speed_level, dtype: int64

sr_pvp_march_speed_level 属性的不同取值和出现的次数
0    228731
1        41
2        11
3         9
4         4
5         2
9         1
6         1
Name: sr_pvp_march_speed_level, dtype: int64

sr_gathering_march_speed_level 属性的不同取值和出现的次数
0     228736
1         37
2         14
4          6
3          3
10         1
7          1
6          1
5          1
Name: sr_gathering_march_speed_level, dtype: int64

sr_outpost_tier_4_level 属性的不同取值和出现的次数
0    228799
1         1
Name: sr_outpost_tier_4_level, dtype: int64

sr_guest_troop_capacity_level 属性的不同取值和出现的次数
0    228799
1         1
Name: sr_guest_troop_capacity_level, dtype: int64

sr_march_size_level 属性的不同取值和出现的次数
0    228799
9         1
Name: sr_march_size_level, dtype: int64

sr_rss_help_bonus_level 属性的不同取值和出现的次数
0    228800
Name: sr_rss_help_bonus_level, dtype: int64

pvp_battle_count 属性的不同取值和出现的次数
0      170932
1       16226
2        9257
3        6021
4        4166
6        3048
5        3019
7        1995
8        1498
9        1248
10       1027
11        894
12        839
13        664
14        615
15        569
16        483
17        423
18        345
19        328
20        314
21        286
22        233
23        210
24        205
26        199
25        195
27        180
28        168
30        157
        ...
234         1
184         1
288         1
164         1
289         1
310         1
231         1
538         1
609         1
273         1
277         1
402         1
229         1
325         1
296         1
196         1
276         1
323         1
168         1
578         1
281         1
450         1
278         1
406         1
240         1
485         1
807         1
152         1
167         1
226         1
Name: pvp_battle_count, Length: 286, dtype: int64

pvp_lanch_count 属性的不同取值和出现的次数
0      203040
1        9273
2        3740
3        2235
4        1496
5        1076
6         882
7         685
8         565
9         477
10        406
11        368
12        338
13        304
14        257
15        231
16        213
18        163
17        149
20        134
22        129
19        124
21        124
24        104
25        104
26        104
23         99
28         78
30         75
27         73
        ...
225         1
171         1
312         1
350         1
182         1
254         1
180         1
563         1
160         1
445         1
233         1
155         1
146         1
332         1
275         1
403         1
203         1
713         1
276         1
201         1
149         1
455         1
179         1
198         1
280         1
235         1
281         1
196         1
195         1
168         1
Name: pvp_lanch_count, Length: 241, dtype: int64

pvp_win_count 属性的不同取值和出现的次数
0      202496
1       10002
2        4181
3        2347
4        1603
5        1105
6         880
7         651
8         562
9         457
10        360
11        316
12        279
14        249
13        219
16        186
15        171
17        145
18        144
19        111
20        103
21        101
22         99
23         75
26         74
24         73
25         73
27         66
30         64
28         62
        ...
382         1
184         1
312         1
294         1
166         1
231         1
159         1
202         1
280         1
110         1
153         1
201         1
283         1
453         1
540         1
195         1
235         1
287         1
549         1
415         1
449         1
233         1
193         1
162         1
488         1
419         1
232         1
192         1
165         1
346         1
Name: pvp_win_count, Length: 252, dtype: int64

pve_battle_count 属性的不同取值和出现的次数
0      154815
1       31070
2       13686
3        6148
4        3536
5        2353
6        1657
7        1266
8        1039
9         884
10        731
11        665
12        560
13        512
14        438
15        376
16        372
17        350
18        309
20        280
19        254
21        238
25        220
24        217
23        212
22        208
27        186
29        183
26        178
28        161
        ...
185         4
187         3
170         3
186         3
196         3
188         2
189         2
190         2
227         2
191         2
195         2
213         2
207         2
242         1
201         1
183         1
198         1
214         1
199         1
205         1
204         1
240         1
218         1
209         1
224         1
210         1
226         1
212         1
232         1
255         1
Name: pve_battle_count, Length: 215, dtype: int64

pve_lanch_count 属性的不同取值和出现的次数
0      155001
1       31020
2       13688
3        6093
4        3521
5        2336
6        1656
7        1263
8        1037
9         883
10        729
11        671
12        553
13        516
14        441
15        380
16        368
17        345
18        306
20        274
19        250
21        237
24        221
25        217
23        214
22        205
27        184
29        180
26        176
28        161
        ...
196         3
187         3
191         3
210         2
206         2
204         2
227         2
190         2
193         2
189         2
194         1
213         1
242         1
240         1
232         1
179         1
226         1
224         1
218         1
214         1
211         1
195         1
183         1
209         1
186         1
188         1
201         1
199         1
198         1
255         1
Name: pve_lanch_count, Length: 216, dtype: int64

pve_win_count 属性的不同取值和出现的次数
0      155704
1       32527
2       14196
3        5911
4        3102
5        2175
6        1527
7        1141
8         894
9         766
10        633
11        519
12        476
13        418
14        395
16        345
15        339
17        283
18        257
20        234
19        231
21        204
24        189
25        186
22        183
23        174
26        171
27        171
29        150
28        148
        ...
183         4
180         4
165         4
155         3
150         3
200         3
169         2
195         2
206         2
196         2
181         2
189         2
143         2
171         2
179         2
182         2
173         2
184         2
187         2
203         1
186         1
222         1
192         1
190         1
216         1
248         1
230         1
188         1
214         1
207         1
Name: pve_win_count, Length: 201, dtype: int64

pay_count 属性的不同取值和出现的次数
0     224599
1       1786
2        792
3        491
4        309
5        209
6        159
7        100
8         77
9         57
11        39
10        35
12        29
13        21
14        20
16        14
15        13
19         8
18         6
17         5
20         5
24         4
22         3
23         3
31         3
21         2
26         2
64         1
25         1
27         1
30         1
34         1
38         1
57         1
61         1
66         1
Name: pay_count, dtype: int64

In [6]:
#对数值型特征，观察其取值范围及直方图
cat_features = train_part1.select_dtypes(include = ["float64"]).columns
for col in cat_features:
    print('\n%s 属性的不同取值和出现的次数' % col)
    print(train_part1[col].value_counts())

wood_add_value 属性的不同取值和出现的次数
0.0           63386
10000.0       23316
11500.0        3612
20125.0        3349
38538.0        1799
43413.0        1644
128252.0       1462
26375.0        1409
84839.0        1266
15500.0        1265
54253.0        1089
18125.0         935
96255.0         902
97666.0         875
129668.0        693
27625.0         651
118252.0        596
211500.0        528
139668.0        498
91817.0         485
210000.0        481
131852.0        443
58404.0         430
21500.0         363
50000.0         348
39038.0         341
28975.0         304
30975.0         299
121852.0        297
220125.0        297
              ...
474269.0          1
343199.0          1
118568.0          1
42901.0           1
474264.0          1
15177077.0        1
237142.0          1
53189.0           1
3794302.0         1
118572.0          1
686436.0          1
686386.0          1
15176446.0        1
474228.0          1
118563.0          1
2745257.0         1
15175598.0        1
948483.0          1
1372685.0         1
343174.0          1
237125.0          1
171592.0          1
1242137.0         1
948513.0          1
109067.0          1
343186.0          1
56322.0           1
686374.0          1
3794084.0         1
227250.0          1
Name: wood_add_value, Length: 80204, dtype: int64

wood_reduce_value 属性的不同取值和出现的次数
0.0           81222
3700.0        10060
8830.0         2813
600.0          2644
1600.0         2571
18424.0        2144
70891.0        1892
4200.0         1887
52467.0        1265
4700.0         1259
25066.0        1224
100585.0       1120
6642.0         1005
119009.0        991
7480.0          819
8750.0          609
5780.0          596
34239.0         562
37314.0         523
9330.0          457
5050.0          420
9830.0          411
18890.0         354
6780.0          312
25140.0         282
10830.0         255
9930.0          252
2100.0          238
10180.0         217
5750.0          204
              ...
85721.0           1
1895807.0         1
10972090.0        1
236974.0          1
85261.0           1
1371495.0         1
77644.0           1
194312.0          1
171432.0          1
15165931.0        1
171431.0          1
685719.0          1
342859.0          1
123422.0          1
26868.0           1
3909778.0         1
230656.0          1
87768587.0        1
123632.0          1
42855.0           1
3791283.0         1
15165105.0        1
3791273.0         1
66849.0           1
10542.0           1
29619.0           1
473902.0          1
53196.0           1
236950.0          1
3641487.0         1
Name: wood_reduce_value, Length: 77604, dtype: int64

stone_add_value 属性的不同取值和出现的次数
0.0           203421
200000.0        3958
20000.0         1830
800000.0        1115
12000.0          451
1000.0           373
40000.0          321
1000000.0        226
24000.0          196
28000.0          187
220000.0         161
3000.0           151
44000.0          124
41000.0          121
50000.0          119
2000.0           113
25000.0           96
16000.0           93
70000.0           89
60000.0           85
32000.0           83
29000.0           82
100000.0          80
10000.0           79
36000.0           79
201000.0          76
48000.0           72
21000.0           70
45000.0           69
250000.0          63
               ...
1894013.0          1
473500.0           1
2739378.0          1
473483.0           1
171203.0           1
3787749.0          1
171196.0           1
1370070.0          1
1370205.0          1
10969767.0         1
118442.0           1
947740.0           1
685570.0           1
685554.0           1
1371035.0          1
21936084.0         1
473815.0           1
473786.0           1
123646.0           1
1895034.0          1
1370227.0          1
947506.0           1
236876.0           1
1370669.0          1
236862.0           1
21928670.0         1
685240.0           1
1894706.0          1
236832.0           1
226240.0           1
Name: stone_add_value, Length: 11677, dtype: int64

stone_reduce_value 属性的不同取值和出现的次数
0.0            218797
191296.0          246
80000.0           136
572848.0          120
656832.0          112
552848.0          104
20000.0            96
757632.0           95
458960.0           90
100000.0           78
472656.0           73
50000.0            54
40000.0            49
200000.0           44
777632.0           43
70000.0            37
378768.0           36
160000.0           36
211296.0           35
40960.0            33
636832.0           29
271296.0           29
478960.0           29
220000.0           28
542944.0           28
60000.0            26
391296.0           25
562944.0           25
120000.0           24
241296.0           22
                ...
1900712.0           1
475280.0            1
42000.0             1
5498050.0           1
687160.0            1
687152.0            1
2745932.0           1
3793308.0           1
686264.0            1
686268.0            1
242807000.0         1
3793954.0           1
474256.0            1
2745480.0           1
1372748.0           1
948568.0            1
3794368.0           1
10984418.0          1
1898584.0           1
7589420.0           1
343296.0            1
2746402.0           1
5492864.0           1
1373264.0           1
171675.0            1
686952.0            1
2748008.0           1
237296.0            1
32000.0             1
645668.0            1
Name: stone_reduce_value, Length: 7023, dtype: int64

ivory_add_value 属性的不同取值和出现的次数
0.0           186876
3000.0         19579
6000.0          4582
200000.0        3203
9000.0          1464
203000.0         802
12000.0          656
15000.0          346
206000.0         323
18000.0          205
100000.0         145
209000.0         136
10000.0          132
500000.0         123
503000.0         115
21000.0          113
13000.0           93
20000.0           85
103000.0          80
212000.0          78
24000.0           77
30000.0           75
16000.0           74
7000.0            71
23000.0           70
1000.0            65
4000.0            63
215000.0          58
106000.0          54
19000.0           49
               ...
83.0               1
1359250.0          1
902000.0           1
1363750.0          1
3784699.0          1
3776510.0          1
1978000.0          1
1367706.0          1
2735031.0          1
1367000.0          1
118200.0           1
683392.0           1
1366385.0          1
945286.0           1
1890250.0          1
1365908.0          1
2731530.0          1
170718.0           1
7559062.0          1
3778764.0          1
1365000.0          1
7557078.0          1
944557.0           1
1364777.0          1
1889000.0          1
2729075.0          1
1364474.0          1
1832000.0          1
7553503.0          1
10427820.0         1
Name: ivory_add_value, Length: 4079, dtype: int64

ivory_reduce_value 属性的不同取值和出现的次数
0.0           226708
230976.0         167
49152.0           62
243776.0          37
430452.0          30
127796.0          30
6400.0            24
237376.0          22
12800.0           20
5430.0            14
25340.0            9
253627.0           9
7240.0             9
443252.0           7
9050.0             6
98304.0            6
181000.0           6
3620.0             6
108600.0           5
537752.0           5
3258.0             5
394976.0           5
54300.0            5
594452.0           5
524952.0           5
50000.0            4
266364.0           4
4887.0             4
280128.0           4
22806.0            4
               ...
15116061.0         1
1365266.0          1
1365541.0          1
683000.0           1
1890364.0          1
3781142.0          1
1366600.0          1
83.0               1
21754841.0         1
470982.0           1
2713953.0          1
1354576.0          1
21678008.0         1
939617.0           1
117457.0           1
1879900.0          1
10847785.0         1
339000.0           1
3776000.0          1
43428205.0         1
7534863.0          1
1357706.0          1
941219.0           1
941252.0           1
2716468.0          1
339576.0           1
7532396.0          1
2717718.0          1
731856.0           1
453000.0           1
Name: ivory_reduce_value, Length: 1513, dtype: int64

meat_add_value 属性的不同取值和出现的次数
0.0           63748
10000.0       23317
11000.0        3578
16375.0        3365
62775.0        1649
84919.0        1479
32000.0        1410
13000.0        1382
38775.0        1318
22144.0        1279
2228.0         1113
29973.0        1056
65003.0         994
62748.0         950
14375.0         944
32625.0         727
54919.0         603
611000.0        529
37028.0         500
610000.0        481
88519.0         442
4253.0          431
35003.0         370
41505.0         370
41000.0         361
37525.0         305
33525.0         304
616375.0        300
32775.0         297
58519.0         292
              ...
171863.0          1
237400.0          1
949601.0          1
1899206.0         1
171865.0          1
10999439.0        1
194249.0          1
144968.0          1
171867.0          1
72446.0           1
11247.0           1
72447.0           1
687362.0          1
171852.0          1
38514.0           1
118689.0          1
45668.0           1
113836.0          1
343687.0          1
42961.0           1
687387.0          1
1899066.0         1
687392.0          1
7596302.0         1
56329.0           1
85925.0           1
466848.0          1
2749616.0         1
1899098.0         1
113703.0          1
Name: meat_add_value, Length: 84271, dtype: int64

meat_reduce_value 属性的不同取值和出现的次数
0.0           81027
2000.0         9968
6220.0         2754
400.0          2658
900.0          2566
9444.0         2060
39044.0        1890
2250.0         1845
2500.0         1276
29600.0        1268
12684.0        1179
66054.0        1172
75498.0        1024
3240.0         1008
3980.0          789
6060.0          587
3220.0          585
19548.0         556
19100.0         515
6470.0          400
2675.0          396
7145.0          382
9656.0          352
3000.0          330
5220.0          291
15066.0         277
63125.0         245
7570.0          235
7220.0          223
10000.0         221
              ...
948020.0          1
150368.0          1
118502.0          1
2743487.0         1
474005.0          1
2743459.0         1
5486906.0         1
25480.0           1
236999.0          1
118499.0          1
36666.0           1
62280.0           1
118498.0          1
685838.0          1
236994.0          1
369776.0          1
96042.0           1
473980.0          1
194314.0          1
75492.0           1
473972.0          1
2743151.0         1
63500.0           1
118491.0          1
10972530.0        1
67656.0           1
86729.0           1
42861.0           1
85721.0           1
582640.0          1
Name: meat_reduce_value, Length: 75447, dtype: int64

magic_add_value 属性的不同取值和出现的次数
0.0          179041
60000.0        2779
1500.0         2151
3000.0          388
300.0           164
21600.0         143
61500.0         140
1.0              55
145126.0         54
4500.0           53
153001.0         53
1800.0           53
147376.0         52
140626.0         49
154126.0         47
6000.0           47
139501.0         47
151876.0         44
23100.0          44
160876.0         43
142876.0         43
130501.0         43
149626.0         43
155251.0         43
144001.0         42
150751.0         41
137251.0         41
159751.0         41
138376.0         40
158626.0         39
              ...
236857.0          1
171325.0          1
118432.0          1
171330.0          1
473738.0          1
685333.0          1
109265.0          1
52766.0           1
29609.0           1
118438.0          1
342687.0          1
21418.0           1
236882.0          1
236884.0          1
1069636.0         1
171350.0          1
85680.0           1
171363.0          1
171366.0          1
59227.0           1
1895275.0         1
59228.0           1
171378.0          1
12145.0           1
42845.0           1
22214.0           1
42846.0           1
171388.0          1
473861.0          1
40370.0           1
Name: magic_add_value, Length: 35805, dtype: int64

magic_reduce_value 属性的不同取值和出现的次数
0.0          190975
1500.0         2347
6000.0         1434
7500.0         1430
122936.0        711
4500.0          435
13500.0         423
10500.0         421
16500.0         346
19500.0         269
21600.0         242
61468.0         222
22500.0         197
3000.0          192
25500.0         133
12000.0         102
100.0            89
28500.0          89
8100.0           85
9000.0           83
43200.0          80
31500.0          41
71000.0          34
2000.0           29
184404.0         27
61500.0          25
4000.0           25
25600.0          24
34500.0          19
300.0            17
              ...
671204.0          1
1823.0            1
32141.0           1
167812.0          1
8610.0            1
83909.0           1
335643.0          1
14585.0           1
281425.0          1
7291.0            1
49493.0           1
167770.0          1
670910.0          1
65648.0           1
670831.0          1
10482.0           1
1028589.0         1
23951.0           1
83861.0           1
233260.0          1
10483.0           1
671056.0          1
41933.0           1
58318.0           1
50872.0           1
128568.0          1
233281.0          1
7619.0            1
20970.0           1
160801.0          1
Name: magic_reduce_value, Length: 23565, dtype: int64

avg_online_minutes 属性的不同取值和出现的次数
0.166667      26356
0.333333      15475
0.500000      13997
0.666667      12819
0.833333       9548
1.000000       6958
1.166667       6275
1.833333       5843
2.000000       5559
1.666667       5260
1.333333       5034
2.166667       4844
1.500000       4819
2.333333       4730
0.000000       4243
2.500000       4007
2.666667       3543
3.333333       3385
3.500000       3284
3.166667       3122
3.666667       3110
2.833333       3086
3.000000       2798
3.833333       2755
4.000000       2318
4.166667       2080
4.333333       1808
4.500000       1606
4.666667       1525
4.833333       1364
              ...
550.666667        1
360.666667        1
489.333333        1
142.666667        1
247.333333        1
552.333333        1
551.666667        1
360.166667        1
489.833333        1
479.833333        1
651.500000        1
324.500000        1
779.500000        1
419.166667        1
228.166667        1
367.666667        1
551.833333        1
322.500000        1
367.166667        1
554.666667        1
494.666667        1
465.000000        1
418.833333        1
554.166667        1
367.833333        1
302.000000        1
349.833333        1
360.333333        1
155.666667        1
547.833333        1
Name: avg_online_minutes, Length: 2397, dtype: int64

pay_price 属性的不同取值和出现的次数
0.00       224599
0.99         1598
1.98          490
6.97          135
5.98          128
2.97          107
16.96          81
11.97          80
10.98          77
4.99           69
1.99           63
2.98           61
3.97           52
9.99           42
26.95          33
15.97          31
11.96          27
36.95          26
8.96           26
21.95          23
3.96           23
31.94          22
4.96           21
10.97          17
7.96           17
36.94          14
26.96          14
41.94          13
46.94          13
12.96          13
            ...
199.98          1
199.89          1
421.83          1
132.92          1
206.82          1
316.89          1
2026.66         1
566.82          1
91.90           1
52.91           1
188.91          1
64.86           1
166.88          1
118.88          1
91.88           1
115.82          1
226.81          1
96.89           1
202.90          1
12.97           1
136.85          1
291.84          1
256.81          1
146.86          1
48.93           1
190.84          1
20.89           1
54.92           1
33.91           1
306.86          1
Name: pay_price, Length: 497, dtype: int64

prediction_pay_price 属性的不同取值和出现的次数
0.00       224161
0.99         1579
1.98          447
5.98          161
6.97          110
1.99           88
4.99           83
2.97           81
2.98           79
10.98          74
3.97           59
11.97          57
16.96          53
9.99           37
10.97          37
15.97          28
7.97           25
8.96           23
11.96          22
20.96          17
26.95          17
21.95          17
3.96           17
12.96          15
4.96           14
36.95          14
19.99          14
18.95          13
7.96           13
5.96           13
            ...
110.80          1
490.70          1
405.40          1
265.79          1
181.90          1
106.87          1
167.82          1
298.70          1
126.92          1
169.80          1
326.87          1
22.90           1
1017.64         1
616.78          1
81.92           1
413.64          1
20.89           1
989.55          1
118.74          1
235.74          1
231.88          1
26.93           1
556.65          1
186.77          1
615.78          1
122.90          1
726.70          1
58.81           1
26.87           1
138.65          1
Name: prediction_pay_price, Length: 940, dtype: int64

In [7]:
#对数值型特征，观察其取值范围及直方图
cat_features = train_part1.select_dtypes(include = ["object"]).columns
for col in cat_features:
    print('\n%s 属性的不同取值和出现的次数' % col)
    print(train_part1[col].value_counts())

register_time 属性的不同取值和出现的次数
2018-02-01 14:17:47    6
2018-03-01 14:51:53    5
2018-02-24 14:47:41    5
2018-02-20 01:12:11    4
2018-02-01 14:17:51    4
2018-02-24 14:47:42    4
2018-02-18 15:32:29    4
2018-02-24 01:18:22    3
2018-03-06 21:02:55    3
2018-01-27 00:50:55    3
2018-02-25 17:18:55    3
2018-02-07 01:13:11    3
2018-02-17 19:24:21    3
2018-02-07 22:05:09    3
2018-02-19 21:39:43    3
2018-02-19 14:34:21    3
2018-02-15 00:16:10    3
2018-02-19 14:20:33    3
2018-02-18 20:22:16    3
2018-02-06 21:58:18    3
2018-02-07 18:07:12    3
2018-02-13 17:47:19    3
2018-02-16 03:24:33    3
2018-02-16 15:07:49    3
2018-02-19 22:49:39    3
2018-02-19 18:05:33    3
2018-02-05 23:18:36    3
2018-01-28 11:50:07    3
2018-02-19 21:53:24    3
2018-02-20 05:38:56    3
                      ..
2018-02-12 05:54:45    1
2018-02-12 12:29:11    1
2018-01-31 21:17:38    1
2018-02-11 03:55:24    1
2018-02-19 11:26:26    1
2018-03-04 14:26:54    1
2018-02-19 02:58:18    1
2018-02-05 20:40:50    1
2018-03-04 21:43:30    1
2018-02-20 21:18:16    1
2018-02-10 22:53:21    1
2018-02-18 02:39:00    1
2018-02-06 19:49:55    1
2018-02-25 10:16:18    1
2018-02-15 20:35:22    1
2018-02-04 15:18:00    1
2018-03-04 13:24:55    1
2018-02-24 11:02:35    1
2018-02-23 22:01:10    1
2018-02-20 11:21:12    1
2018-02-28 23:12:57    1
2018-02-11 16:25:25    1
2018-02-27 08:28:53    1
2018-02-02 13:49:46    1
2018-02-19 00:26:45    1
2018-02-26 19:57:18    1
2018-02-05 16:07:46    1
2018-01-31 13:21:12    1
2018-01-27 19:22:14    1
2018-02-08 03:47:24    1
Name: register_time, Length: 220450, dtype: int64